import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Footer from "./_components/footer";
import NavbarWrapper from "./_components/navbarWrapper";
import Navbar from "./_components/navbar";
import UserContextProvider from "./contex/UserContextProvider";
;

export const metadata = {
  title: "shamar news",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
      <UserContextProvider>
          <NavbarWrapper />
          {/* <Navbar/> */}
        <div className="main-content">
          {children}
        </div>
        <Footer />
       </UserContextProvider>
      </body>
    </html>
  );
}
